version: '3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'iaddb'
      MYSQL_USER: 'iad'
      MYSQL_PASSWORD: 'iad'
      MYSQL_ROOT_PASSWORD: 'root'
    command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - mysqlenv
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - mysqlenv
networks:
  mysqlenv:
volumes:
  database:
