version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'iaddb'
      MYSQL_USER: 'iad'
      MYSQL_PASSWORD: 'iad'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
  # admin:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
volumes:
  database:
